### ISSUE TITLE
sim$data returning NAs when individual replicates have larger sums

### ISSUE THREAD

**Issue by zterner-mitre** [RobinDenz1/simDAG#1]
[simDAG Github code copy.txt](https://github.com/RobinDenz1/simDAG/files/14201748/simDAG.Github.code.copy.txt)

Building from the example [here](https://cran.r-project.org/web/packages/simDAG/vignettes/v_covid_example.html), I am trying to build a DAG for covid infections with the following components:

- People can get two shots of one vaccine (but represented in one vaccine node with two durations)
- People who are vaccinated mask less
- Masking is a mediator of how sick people get (so that folks who mask get sick less often than those who don't)

I have defined a few functions by modifying the base ones in the vignette, as shown in the attached file. I hope these are right, but there may be an error in here causing some issues.

I am writing because I am comparing the sums in sim2$data vs the sums in individual past states, and the individual past states are recording many more events and more often than one would expect from looking at sim2$data. Is that supposed to be happening? (This comparison happens at the end of the code).

As an aside, it seems that the vignette has some functionality which is not documented in the [PDF on CRAN](https://cran.r-project.org/web/packages/simDAG/simDAG.pdf), so apologies if this is no longer being maintained or if I am looking in the wrong place. I have gone through all the tutorials and tried to work through this as well as possible.

I am attaching an R script to reproduce the problem since the code was formatting poorly when pasting it in here. I gave it a .txt extension because Github did not accept the .R extension.

Thanks so much for your thoughts and time!
Zach

**Comment by RobinDenz1** [comment]
Thanks for your interest in this package and for supplying your code alongside your request.

You said: "the individual past states are recording many more events and more often than one would expect from looking at sim2$data. Is that supposed to be happening?":

Yes this is not a bug. The `data` output only stores the state of the simulation at the last point in time. If your simulated individuals are experiencing an event at this time, it will show up in `data`. However, if they have experienced an event in the past and the `event_duration` is already over, this event will not show up in `data`, since their event status will have been reset already. The timings of all events are stored in the `tte_past_events` object in the output. If you want to extract a usefull dataset out of the output object, I would recommend using the `sim2data()` function, which directly uses those actual event times to construct the dataset. In your code, for example, you could add

```R
sim_dat <- sim2data(sim2, to="long")
```

in line 232 and would receive a correct dataset in the long format. I know this is a little weird, but it's the fastest and most memory efficient way I could come up with to get useful output. If you have any suggestions on how to improve the documentation to make this more clear I would be very happy.

Additionally, you asked: "it seems that the vignette has some functionality which is not documented in the PDF on CRAN". Which functionality seems to be missing?

Best wishes,
Robin

**Comment by zterner-mitre** [comment]
Update: it seems like the base_p for vaccination is working out to be the probability that people get vaccinated over the course of _the whole simulation_. Am I interpreting that correctly? For instance, if I change base_p to .80 (within the vaccination node), then I find this distribution, indicating that only 20% of people never got a vaccine.

<img width="760" alt="image" src="https://github.com/RobinDenz1/simDAG/assets/117375468/98a1e395-74f2-44b3-b507-cfd6c6397164">

I'm also attaching the script with this simulation for completeness.
[simDAG 2 copy.txt](https://github.com/RobinDenz1/simDAG/files/14216066/simDAG.2.copy.txt)

**Comment by RobinDenz1** [comment]
I think there are some slight misconceptions on how the simulation works.

For every time-to-event node, you have to define a function that computes the probability of the person getting the event at a single point in time, possible given covariates or past states of the variable itself. In the vignette, this is what I did starting at "part 2". The `vacc_duration` argument is not an argument of `node_td()`, `sim_discrete_time()` or any other function included in the package, it is an argument of the specific probability function `prob_covid()` that I defined in the vignette, similar to `base_p` or `rr_covid` etc. Since you are definining the node using `node_td()` you have to specify these arguments in the `node_td()` call.

This function with all of it's arguments is called at every single point in time of your simulation. So for instance at `t = 1` in your last example, the `prob_vaccination()` function is called first to estimate the probability of a person getting vaccinated at `t = 1`. You coded it in such a way that this probability will be zero while the `covid` event is still ongoing and `base_p` otherwise. So at `t = 1` it will be `base_p` for everyone. This probability is used to draw the vaccination status. By setting `base_p=0.8` you ensure that about 80% of all people will be vaccinated right away. You can check this by looking at the number of vaccination events that were recorded at `t = 1` using: `length(sim2$tte_past_events$vaccination[[1]])`.

You set `event_duration` to 5 and `immunity_duration` to 21 in the respective `node_td()` call, which means that the `vaccination_event` variable will stay `TRUE` for 5 points in time and will stay at `FALSE` for the 16 time points thereafter. Now the `covid` status is generated in the same way. The `prob_covid2` function is called to generate the probability of a person receiving covid at `t = 1`. The approximately 80% of your population who are vaccinated will have `base_p1` probability of getting covid etc.

Apart from that I can also see at least one issue with your code. You use the line `ifelse(data$vaccination_time_since_last < vacc_duration1, base_p1, ifelse(data$vaccination_time_since_last < vacc_duration2, base_p2, base_p))` inside your `prob_covid2()` function. This results in NA values for all non-vaccinated persons, because the `vaccination_time_since_last` variable is NA if the person was never vaccinated before.

I appreciate your interest, but unfortunately I do not have more time to help you debug your code. I would recommend starting with a very simple model to help you understand the workings of this admittedly quite unwieldy simulation framework. If you find any actual bugs or have specific feature requests, please don't hesitate to let me know!
