### ISSUE TITLE
Example w/ Poisson variable

### ISSUE THREAD

**Issue by torkar** [RobinDenz1/simDAG#4]
I'm playing around with your package (nice work!) to see if I can use it in education. But I seem to have stumbled a bit on the syntax and can't find anything in the help pages or vignettes.

I want to create an example where we have a Gaussian confounder $C$ pointing at a treatment $X$ (Poisson) and outcome $Y$ (Poisson). In addition, $X$ causes $Y$ also of course.

```
dag <- empty_dag() +
  node("X", type = "poisson", intercept = 2) +
  node("Y", type = "poisson", intercept = 1) +
  node("C", type = "gaussian", parents = c("X", "Y"),
       betas = c(0.2, 0.5), intercept = -2, error = 2)
```
Unfortunately, I get `Error in (function (link = "log")`. I assume the intercept is $\lambda$ in the case of Poisson?

Additionally, I want to check that I understand correctly how to make sure to add X to Y, i.e., adding `parents = "X", betas = 1)` to the node $Y$?

**Comment by RobinDenz1** [comment]
Thanks for the kind words.

It is certainly not the cleanest syntax, I agree. In essence you have to specify a regression model (or other function) that specifies each node. In your example, you would do something like this:

```R
dag <- empty_dag() +
  node("C", type="rnorm", mean=0, sd=1) +
  node("X", type="poisson", parents="C", intercept=1, betas=-0.5) +
  node("Y", type="poisson", parents=c("C", "X"), betas=c(0.2, 0.5),
       intercept=-2)
```
You can check that this is indeed what you want by calling the `plot()` function, or (in the developmental version) you can use the `summary()` function to directly print the underlying structural equations.

Since $C$ is not caused by anything it should have no `parents`. Instead, it should be a function that generates $n$ samples from some distribution. If you want to generate a gaussian variable, you would use the `rnorm()` function, hence we would set `type="rnorm"`. Further arguments such as `mean` and `sd` are then passed to it under the hood.

Since $X$ depends only on $C$ you should specify `parents="C"` and define a suitable regression model, where $X$ is the outcome and $C$ is the only predictor. Same goes for $Y$, with the small change that this variable depends on both $C$ and $X$. Does that make it more clear? Any ideas on how to improve the documentation are highly welcome as well.

**Comment by torkar** [comment]
Sorry, I should've written collider and not confounder... My fault. I'll see if I can get this done now :)

**Comment by RobinDenz1** [comment]
No problem. Please let me know if you were able to do it, otherwise I can give you an example.

**Comment by torkar** [comment]
Robin,

something like this?
```
dag <- empty_dag() +
  node("X", type="rpois", lambda = 2) +
  node("Y", type="poisson", parents=c("X"), betas=c(0.5),
       intercept=-2) +
  node("C", type="gaussian", parents = c("X", "Y"), betas = c(0.2, 0.8),
       intercept = 0.5, error = 2)
```

seems ok.

**Comment by torkar** [comment]
I really like this pkg Robin. I will likely use it in my course after summer. What tripped me up was the difference between, e.g., `rpois` and `poisson`, and `rnorm` and `gaussian`. Nice work. I'll play with it a lot doing summer :)

**Comment by RobinDenz1** [comment]
I am glad to hear you like it! Don't hesitate to let me know if you ever have further questions or suggestions.
